/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 keyboard.gltf --transform
Author: Nick.Stark (https://sketchfab.com/Nick.Stark)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/keyboard-c76ee51ba10a49218e63b050a99b1f33
Title: Keyboard
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/keyboard-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001__0.geometry} material={materials['Scene_-_Root']} position={[55.88, 147.5, 193.75]} scale={20.76} />
    </group>
  )
}

useGLTF.preload('/keyboard-transformed.glb')
