/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 figma.gltf --transform
Author: vijay verma (https://sketchfab.com/realvjy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/figmafbx-8c7e55c2ef074f559098fe9267ab79b6
Title: figma.fbx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {


  const { nodes, materials } = useGLTF('/figma-transformed.glb')

  const greenMaterial1 = materials['Color_-_Figma_Green'].clone();
  greenMaterial1.color.set(0x00ff00); // set color to red

  const greenMaterial2 = materials['Color_-_Figma_Green'].clone();
  greenMaterial2.color.set(0xff0000); // set color to green

  const greenMaterial3 = materials['Color_-_Figma_Green'].clone();
  greenMaterial3.color.set(0xfa5f5f); // set color to blue

  const greenMaterial4 = materials['Color_-_Figma_Green'].clone();
  greenMaterial4.color.set(0xb25ffa); // set color to blue

  const greenMaterial5 = materials['Color_-_Figma_Green'].clone();
  greenMaterial5.color.set(0x619eff); // set color to blue



  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={80}>
          <mesh geometry={nodes['Cylinder006_Color_-_Figma_Green_0'].geometry} material={greenMaterial1} />
          <mesh geometry={nodes['Cylinder006_Color_-_Figma_Red_0'].geometry} material={greenMaterial2} />
          <mesh geometry={nodes['Cylinder006_Color_-_Figma_Light_Red_0'].geometry} material={greenMaterial3} />
          <mesh geometry={nodes['Cylinder006_Color_-_Figma_Sky_0'].geometry} material={greenMaterial5} />
          <mesh geometry={nodes['Cylinder006_Color_-_Figma_Violet_0'].geometry} material={greenMaterial4} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/figma-transformed.glb')
