/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 figma.gltf --transform
Author: vijay verma (https://sketchfab.com/realvjy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/figmafbx-8c7e55c2ef074f559098fe9267ab79b6
Title: figma.fbx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/figma-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes['Cylinder006_Color_-_Figma_Green_0'].geometry} material={materials['Color_-_Figma_Green']} />
          <mesh geometry={nodes['Cylinder006_Color_-_Figma_Red_0'].geometry} material={materials['Color_-_Figma_Green']} />
          <mesh geometry={nodes['Cylinder006_Color_-_Figma_Light_Red_0'].geometry} material={materials['Color_-_Figma_Green']} />
          <mesh geometry={nodes['Cylinder006_Color_-_Figma_Sky_0'].geometry} material={materials['Color_-_Figma_Sky']} />
          <mesh geometry={nodes['Cylinder006_Color_-_Figma_Violet_0'].geometry} material={materials['Color_-_Figma_Green']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/figma-transformed.glb')
